version: '3.8'

services:
  order-service:
    build: ./OrderService
    container_name: order-service
    restart: always
    ports:
      - "6000:4000"
    env_file:
      - ./OrderService/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    networks:
      - app-network

  payment-service:
    build: ./PaymentService
    container_name: payment-service
    restart: always
    env_file:
      - ./PaymentService/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      order-service:
        condition: service_started
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27019:27017"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5674:5672"
      - "15674:15672"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
